# FIXME: CREATE THEME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# https://github.com/gyscos/cursive/blob/main/cursive/examples/assets/style.toml
# https://github.com/gyscos/cursive/blob/main/cursive/examples/theme.rs